Add Mathieu Hofman (MHN)
tc39/notes pull request #28
Opened 2020-02-04 20:09 UTC by robpalme

2020-02-24 14:57 UTC, codehag commented
@robpalme there is a Michal Hollman (MHN) with that abbreviation. Can you use a different one? For example MUH or MHO?

2020-03-24 15:38 UTC, codehag commented
ping @robpalme

2020-03-31 03:35 UTC, pouwerkerk approved these changes
Thank you for adding Mathieu!

2020-03-31 03:35 UTC, pouwerkerk commented on delegates.txt
> +Mathieu Hofman (MHN)
👍

2020-03-31 03:36 UTC, ljharb commented on delegates.txt
> +Mathieu Hofman (MHN)
https://github.com/tc39/notes/pull/28#issuecomment-590362129

2020-03-31 03:38 UTC, pouwerkerk requested changes
Oh, I misunderstood the comment, I'll add a commit with an unused abbreviation.

2020-03-31 03:51 UTC, pouwerkerk commented
I added a separate PR, namely #34, so @robpalme doesn't have to merge in my change before it could be added to this PR. Thanks again for doing the initial work, @robpalme!

2020-03-31 07:37 UTC, codehag commented
closing in favor of #34

2020-03-31 07:37 UTC, closed without merging