Add `Septs (SEP)`
tc39/notes pull request #70
Opened 2020-09-09 05:32 UTC by septs

2020-09-09 05:49 UTC, Jack-Works commented
From Sujitech

2020-09-09 16:32 UTC, mpcsh requested changes
it looks like this rearranges some of the other delegates in the file. also, I don't actually see the new addition anywhere.

2020-09-10 15:34 UTC, mpcsh approved these changes

2020-09-10 20:18 UTC, MylesBorins approved these changes
LGTM

2020-09-10 20:18 UTC, merged